### ISSUE TITLE
[Anon] Skaven: Ability Endless vermintide is missing

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#105]
**Problem:**
Ability Endless vermintide is missing

**Expected:**
Gets Added to the Battletraits

**List:** https://www.newrecruit.eu/app/list/wporV
**Unit:** Battle Traits: Skaven, id: 706f-237e-b646-2049

**Comment by exaegrum** [comment]
endless vermintide is an ability on the gnawhole, not a battletrait.
