### ISSUE TITLE
[Anon] Stormcast Eternals: SCE List says I have 2 more regiments than allowed, when I only have 1 regiment

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#123]
**Problem:**
SCE List says I have 2 more regiments than allowed, when I only have 1 regiment

**Expected:**
Doesn't give the error when using this list configuration

**List:** https://www.newrecruit.eu/app/list/xKTv8

**Comment by exaegrum** [comment]
You have too many units _in_ your regiment.
