### ISSUE TITLE
[Anon] Lumineth Realm-lords: According to the WH AoS app, The Light of Eltharion can have 1 Lumineth Paragon in the regiment and the Bannerblade can join a regiment as paragon, but it is still shown as error

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#161]
**Problem:**
According to the WH AoS app, The Light of Eltharion can have 1 Lumineth Paragon in the regiment and the Bannerblade can join a regiment as paragon, but it is still shown as error

**Expected:**
I can add both Vanari Bannerblade and Light of Eltharion to the same regiment

 **Additional Info:**
WH Aos 4.0 app

**List:** https://www.newrecruit.eu/app/list/PNRmt

**Comment by exaegrum** [comment]
Add the bannerblade under the HERO section and not the Regimental Leader one.
