### ISSUE TITLE
[Anon] Seraphon: Aggradon Lancers doesn't have a "standard" Aggradon Lancer model option, won't allow selection of full model count if reinforced

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#170]
**Problem:**
Aggradon Lancers doesn't have a "standard" Aggradon Lancer model option, won't allow selection of full model count if reinforced

**Expected:**
Should be able to select a non-champion/musician/standard-bearer Aggradon Lamcer

**List:** https://www.newrecruit.eu/app/list/CuSBp
**Unit:** Aggradon Lancers, id: 30e7-b18c-2abe-e02

**Comment by exaegrum** [comment]
Add another model in the NR interface.
