### ISSUE TITLE
[Anon] Ironjawz: Ardboy Big Boss is added to an regiment with an exisiting hero - Regiment is shown as invalid.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#216]
**Problem:**
Ardboy Big Boss is added to an regiment with an exisiting hero - Regiment is shown as invalid.

**Expected:**
Ardboy Big Boss can be added as a headstompa, so the regiment should still be vaild.

**List:** https://www.newrecruit.eu/app/list/qS43t

**Comment by exaegrum** [comment]
Warchanters cant take headstompas. Only Gordrakk and megabosses can.
![image](https://github.com/user-attachments/assets/d441abe7-888b-4100-adb0-b9117f8b4e3a)
