### ISSUE TITLE
[Anon] Idoneth Deepkin: Wood Elf Wizards don't use wood elf magic

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#224]
**Problem:**
Wood Elf Wizards don't use wood elf magic

**Expected:**
They should use special wood elf magic, where they can place woods, teleport between them, etc... Don't know exactly but it should be in the book.

**List:** https://www.newrecruit.eu/app/list/Ng5xf

**Comment by exaegrum** [comment]
I have no idea what you're talking about here. This isn't a Sylvaneth army, and while placing woods can be done with a spell teleporting is just a battle trait? Those can be found if you make a Sylvaneth list.
