### ISSUE TITLE
[Anon] Idoneth Deepkin: No "ordinary" morrsarr guard

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#231]
**Problem:**
No "ordinary" morrsarr guard

**Expected:**
Allow one "no-tag" guard for reinforced unit

**List:** https://www.newrecruit.eu/app/list/KwFT8
**Unit:** Akhelian Morrsarr Guard, id: e35d-db1a-234e-85e

**Comment by exaegrum** [comment]
can be added seperately when reinforced
