### ISSUE TITLE
[Anon] Daughters of Khaine: Currently a regiment can have 4 non hero units in newrecruit, but you can only have 0-3 according to the rules

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#234]
**Problem:**
Currently a regiment can have 4 non hero units in newrecruit, but you can only have 0-3 according to the rules

**Expected:**
An error should pop up when you have more than 3 units in a regiment

**List:** https://www.newrecruit.eu/app/list/7FtMD

**Comment by exaegrum** [comment]
Your generals regiment can have 4, not 3.
