### ISSUE TITLE
[Anon] Kruleboyz: Kruleboyz heros list wrong only the Killaboss with Stab-grot is there while all other heros are only on the leader list 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#248]
**Problem:**
Kruleboyz heros list wrong only the Killaboss with Stab-grot is there while all other heros are only on the leader list 

**Expected:**
Units like the Murknob with Belcha-banna and Swampcalla Shaman with Pot-grot should be available as heros

**List:** https://www.newrecruit.eu/app/list/2Qfde

**Comment by exaegrum** [comment]
![image](https://github.com/user-attachments/assets/35db09ae-830d-42e4-887c-db3de0ffafae)
No, they shouldn't. Only the killaboss with stab-grot can be taken as a secondary hero.
