### ISSUE TITLE
[Anon] Idoneth Deepkin: Won't let me reinforce this unit 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#260]
**Problem:**
Won't let me reinforce this unit 

**Expected:**
I should be able to reinforce but since I can only have one champ and there's no option to add a non musician/champ/standard bearer. I can only add 5 models to the unit 

**List:** https://www.newrecruit.eu/app/list/4wuBd
**Unit:** Akhelian Ishlaen Guard, id: b8aa-232f-d530-85a6

**Comment by exaegrum** [comment]
split one model into a different stack
