### ISSUE TITLE
[Anon] Flesh-eater Courts: No "regular" Morbeg Knight profile, only champion, musician, and standard bearer



### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#261]
**Problem:**
No "regular" Morbeg Knight profile, only champion, musician, and standard bearer

**Expected:**
Ability to add a non specialist Morbeg Knight profile to a unit.

**List:** https://www.newrecruit.eu/app/list/KVoMT
**Unit:** Morbheg Knights, id: 22bc-63f8-b1cd-b8e8

**Comment by exaegrum** [comment]
You can add one by splitting out a model.
