### ISSUE TITLE
[Anon] Stormcast Eternals - Ruination Brotherhood: Ionus Cryptborn cannot be added to ruination brotherhood

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#263]
**Problem:**
Ionus Cryptborn cannot be added to ruination brotherhood

**Expected:**
Ionus Cryptborn should be able to be added to ruination brotherhood 

 **Additional Info:**
https://assets.warhammer-community.com/eng_aos4-battle-profiles-and-rules-updates-december-2024-yk41wti6vv-0byjpq3fz5.pdf

**List:** https://www.newrecruit.eu/app/list/4mYe4

**Comment by exaegrum** [comment]
You cannot actually build a legal list with him. Iridan must be the general, but Ionus has WARMASTER. In order for him to be able to be taken in Ruination Brotherhood, Iridan needs the errata Bastian got to be a WARMASTER in the AoR.
