### ISSUE TITLE
[Anon] Slaves to Darkness - Legion of the First Prince: On mobile I cannot add regiments despite attempting to follow the instructions. If I can add regiments it is not clear on how to do so. 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#265]
**Problem:**
On mobile I cannot add regiments despite attempting to follow the instructions. If I can add regiments it is not clear on how to do so. 

**Expected:**
As above

**List:** https://www.newrecruit.eu/app/list/iHbWH

**Comment by exaegrum** [comment]
Reset your theme. + button is bugged out.
