### ISSUE TITLE
Seraphon Units with Too Many Selections by Default

### ISSUE THREAD

**Issue by otterpopd** [BSData/age-of-sigmar-4th#28]
The following units start with too many selections by default:
Hunters of Huanchi with Dartpipes
Hunters of Huanchi with Starstone Bolas
Kroxigor
Kroxigor Warspawned
Saurus Guard
Saurus Warriors
Skinks
Aggradon Lancers
Raptadon Chargers
Raptadon Hunters
Ripperdactl Riders
Ripperdactl Riders (2 models)
Terradon Riders
Terradon Riders (2 mdels)

The following units also have an incorrect unit size by default
Ripperdactl Riders (2 models)
Terradon Riders (2 models)

I would add all of the screenshots I took but it's 14 units, so here's a selection of just a few
![Uploading IMG_4995.jpeg…]()

![IMG_5001](https://github.com/user-attachments/assets/9aad0d77-90f8-4af6-b43e-f34aa1000ac9)

![IMG_4994](https://github.com/user-attachments/assets/0c75da36-c495-40ee-9992-f373b71a2019)

**Comment by exaegrum** [comment]
I've fixed most of these - the kroxigor special weapons and undersize units are gonna take a bit more, as there's some limitations on New Recruit's end that I'm trying to figure out how to architect the data to get around.
