### ISSUE TITLE
[Anon] Ironjawz: Regiments of Renown abilities missing

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#288]
**Problem:**
Regiments of Renown abilities missing

**Expected:**
Need to see the specials rules for regiment of renown units when selected

 **Additional Info:**
Rules missing

**List:** https://www.newrecruit.eu/app/list/Rvytw

**Comment by MagicPunk** [comment]
Found it in the non custom view. You need to select it there. Issue can be closed.
