### ISSUE TITLE
[Anon] Sylvaneth: When I export my list as Text, there is a unit of Gossamid Archer's missing

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#40]
**Problem:**
When I export my list as Text, there is a unit of Gossamid Archer's missing

**Expected:**
There should be another Gossamid unit in my Belthanos Regiment when I export it to txt

**List:** https://www.newrecruit.eu/app/list/wafNU

**Comment by giloushaker** [comment]
Fixed in nr but not yet release, can mark as resolved.
