### ISSUE TITLE
Seraphon: Regiment Options for Skink Starpriest or Favoured Spawning

### ISSUE THREAD

**Issue by magik930** [BSData/age-of-sigmar-4th#45]
**Describe the bug**
List errors when adding Skink Starpriest or Saurus Astrolith Bearer to regiments containing certain leaders that allow them to bring supplemental heroes.

**To Reproduce**
1. Created a new list.
2. Created a new regiment.
3. Added a hero to that regiment with a Regiment Option which allows for the addition of 0-1 Skink Starpriest or Favoured Spawning
4. Added the Skink Starpriest
5. Errors (1) Regiment has 1 selections too many of Regimental Leader (max 1)

**Expected behavior**
If the hero has a Regiment Option which allows for a Skink Starpriest or Favoured Spawning, these supplemental units should be able to be added to the regiment without creating a conflict.

**Screenshots**

**Device and data (please complete the following information):**
 - OS: iOS, Mac, Windows
 - App being used to create lists: New Recruit
 - App version: v264.8
 - Data release version:

**Additional context**
<img width="1552" alt="Greenshot 2024-09-20 03 50 57" src="https://github.com/user-attachments/assets/49416305-4566-4586-82e6-c735e1a0eacb">
![IMG_E63900AE7B3A-1](https://github.com/user-attachments/assets/9a428285-7993-482a-8512-996799ac20ec)

**Comment by magik930** [comment]
Here's a list of which hero units have which permissions:

The **Saurus Astrolith Bearer** is currently the only unit that can be a Favoured Spawning.

### Regiment Options
#### 0-1 Skink Starpriest or Favoured Spawning

- Lord Kroak
- Slann Starmaster

#### 0-1 Favoured Spawning

- Saurus Oldblood (on foot)
- Saurus Oldblood on Carnosaur
- Saurus Scar-Veteran on Aggradon
- Saurus Scar-Veteran on Carnosaur

**Comment by exaegrum** [comment]
You're adding them from the wrong place. In your first screenshot, look at the list to the left - you're picking the Starpriest from the Regimental Leader section. If you look right underneath, you'll see a HERO section. Add the Starpriest from there.
