### ISSUE TITLE
[Anon] Ironjawz: General keyword not displayed in app

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#46]
**Problem:**
General keyword not displayed in app

**Expected:**
General keyword should be applied in list export

**List:** https://www.newrecruit.eu/app/list/EhbBd

**Comment by exaegrum** [comment]
![Screenshot_20240921-104543_Chrome](https://github.com/user-attachments/assets/1a935924-ea6e-4689-890e-ced72bdf850c)
