### ISSUE TITLE
[Anon] Skaven: Verminlord warpseer and grey seer should be able to take any skaven unit but I can't select the units

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#75]
**Problem:**
Verminlord warpseer and grey seer should be able to take any skaven unit but I can't select the units

**Expected:**
Should be able to select any skaven units if either of those are my regiment leader

**List:** https://www.newrecruit.eu/app/list/KiDjD

**Comment by exaegrum** [comment]
Is there a particular unit missing...? They seem to work just fine.
