### ISSUE TITLE
[Anon] Nighthaunt: Nighthaunt infantry units are not appearing when making a list

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#77]
**Problem:**
Nighthaunt infantry units are not appearing when making a list

**Expected:**
Nighthaunt infantry units being accessible for selection 

**List:** https://www.newrecruit.eu/app/list/vqNLA

**Comment by exaegrum** [comment]
![image](https://github.com/user-attachments/assets/5ced8a72-828d-4f5c-8b3f-8d653e3e18d6)
Not a bug. Knight of Shrouds on Ethereal Steed can't take INFANTRY with it. Add your desired INFANTRY to a different HERO's regiment.
