### ISSUE TITLE
[Anon] Ironjawz: This Battle Formation keeps duplicating when I select it 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/age-of-sigmar-4th#78]
**Problem:**
This Battle Formation keeps duplicating when I select it 

**Expected:**
Not duplicate

**List:** https://www.newrecruit.eu/app/list/hFbNC
**Unit:** Battle Formation[2], id: 1218-968b-bd6e-351e

**Comment by exaegrum** [comment]
Can you send a screenshot of what's happening? I cannot reproduce this.
